# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b630dbf31f3d968208399ae0a057428148c094000233faa0388139ffd616dc535ff9bb40932cf4f9eff7780baadec7e6c2c733564fa528ea6d5c9a43bf7e30

test:
  secret_key_base: a959ca24a981f52a30965ecc5c3e812efe1135954000a2854783153cdbdc719beddae441eac98ca7cf2e1e757036d52706270d9636de82b8f03b07337bba73dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
