Nation.create(name: 'Italia')
Nation.create(name: 'Spagna')
Nation.create(name: 'Francia')
Nation.create(name: 'Brasile')
Nation.create(name: 'Russia')
Nation.create(name: 'Cina')
Nation.create(name: 'Messico')
Nation.create(name: 'Estonia')

SportEvent.create(winner_id: 3, name: '100 metri', location: 'Foro Italico', sport: 'Atletica Leggera')
SportEvent.create(winner_id: 1, name: 'Salto in lungo', location: 'Tor Vergata', sport: 'Atletica Leggera')
SportEvent.create(winner_id: 4, name: 'Salto in alto', location: 'Nuova Fiera di Roma', sport: 'Atletica Leggera')
SportEvent.create(winner_id: 2, name: '400 m stile libero', location: 'Tor Vergata', sport: 'Nuoto')
SportEvent.create(winner_id: 1, name: '100 m rana', location: 'Foro Italico', sport: 'Nuoto')
SportEvent.create(winner_id: 3, name: '200 m misti', location: 'Nuova Fiera di Roma', sport: 'Nuoto')

User.create(name: 'Michele A.', nation_id: 1, email: 'michele@gmail.com', password: 'password_1', password_confirmation: 'password_1')
User.create(name: 'Luca B.', nation_id: 2, email: 'luca@gmail.com', password: 'password_2', password_confirmation: 'password_2')

Bar.create(name: 'Bar Rosso', address: 'Via della Ricerca Scientifica 1', phone: '012345', email: 'bar_rosso@gmail.com')
Bar.create(name: 'Roxy Bar', address: 'Via Dei Girasoli 2', phone: '056471', email: 'roxy_bar@gmail.com')
Bar.create(name: 'Da Mario', address: 'Via Delle Nespole 3', phone: '019845', email: 'da_mario@gmail.com')

GameBet.create(user_id: 1, sport_event_id: 1, winner_id: 2, bar_id: 1)
GameBet.create(user_id: 2, sport_event_id: 3, winner_id: 1, bar_id: 2)
GameBet.create(user_id: 1, sport_event_id: 5, winner_id: 1, bar_id: 2)
GameBet.create(user_id: 2, sport_event_id: 2, winner_id: 1, bar_id: 2)
GameBet.create(user_id: 2, sport_event_id: 4, winner_id: 2, bar_id: 2)
